#!/bin/bash
#SBATCH --partition=rome
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=01:00:00
#SBATCH --output=slurm_logs/%x_%j.out
#SBATCH --error=slurm_logs/%x_%j.err
#SBATCH --job-name=postprocess

set -euo pipefail

START_TIME=$(date +%s)
trap 'END_TIME=$(date +%s); echo "total elapsed time: $((END_TIME - START_TIME)) seconds"' EXIT

PROJECT_DIR="$HOME/ai_medical_imaging_group28/"
VENV_DIR="${PROJECT_DIR}/ai4mi"

module purge
module load 2025
module load Python-bundle-PyPI/2025.04-GCCcore-14.2.0

source "${VENV_DIR}/bin/activate"
cd "${PROJECT_DIR}"

python postprocess_run.py --config "$@"

echo "done"
